app/urls.py
from django.urls import path
from app.views import *
app_name='app'

urlpatterns = [
    path('home/',home,name="home"),
    path('register/',register,name="register"),
    path('login/',login_user,name='login'),
    path('logout/',logout_user,name='logout'),
    path('forgetpassword/',forgetpassword,name="forgetpassword"),
    path('vcode/',vcode,name="vcode"),
    path('reset_password/',reset_password,name="reset_password"),
    path('history/',history,name="history"),
    path('contact/',contact,name="contact"),
    path('resp/',resp,name="resp"),
    
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include
import app
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
]

templates/app/contact.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>weather</title>

  <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mdb.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
	<style>
		body{
			min-height: 100vh;
			background: url("{% static 'images/snow4.jpg' %}") no-repeat fixed;
			background-size: cover;
		}   
	</style>
</head>
<body>
	<nav class="navbar navbar-expand-lg">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarRightAlignExample"
        aria-controls="navbarRightAlignExample"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars text-light m-3"></i>
      </button>
  
      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarRightAlignExample">
        <!-- Left links -->
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          
          <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:home' %}" >Home</a>
          </li>
  
          <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:register' %}">Register</a>
          </li>
          {% if user.is_authenticated and not user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:history' %}">History</a>
          </li>
          <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:login' %}">Login</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:contact' %}" >Contact</a>
          </li>
        </ul>
        <!-- Left links -->
      </div>
      <!-- Collapsible wrapper -->
    </div>
    <!-- Container wrapper -->
  </nav>

<div class="container box">
    <div class="row justify-content-center">
        <div class="col-md-2">
            <h2 class="contactheading text-center">CONTACT</h2>
        </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-8">
          <p class="text-center">Consumers want more than one way to get in touch with companies. While some customers want to talk on the phone, others may prefer to send an email if they’re busy and don’t have the time to sit on a call. A good Contact Us page features an array of options.Providing different types of contact options is especially important if you want to deliver convenient, 24/7 support. Self-service tools—such as AI-powered chat, FAQs, and knowledge base articles—help customers find the answers they need outside your business hours.</p>
      </div>
  </div>

	<div class="row justify-content-around align-items-center">
    <div class="col-md-4">
        <i class="fa-solid fa-location-dot" style="color: white;"></i><h6 style="display: inline;"> Address</h6>
        <p>Aswath Nagar, Marathahalli,<br>Bangalore, Karnataka, <br>560037</p><br>
        <i class="fa-solid fa-phone" style="color: white;"></i><h6 style="display: inline;"> Phone</h6>
        <p>+91-1234567890</p><br>
        <i class="fa-solid fa-envelope" style="color: white;"></i><h6 style="display: inline;"> Email</h6>
        <p>rvijay50658@gmail.com</p><br>
        <i class="fa-brands fa-github" style="color: white;"></i><h6 style="display: inline;"> GitHub Profile</h6>
        <p><a href="https://github.com/Rajavijay50">github.com/Rajavijay50</a></p>


    </div>
    <div class="col-md-4">
        <form method="POST" onsubmit="return validateform()">
          {% csrf_token %}
            <!-- Name input -->
            <div class="form-outline mb-4">
              <input type="text" id="name" name="name" class="form-control text-input" />
              <label class="form-label" for="name"><p>Name</p></label>
            </div>
          
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="email" id="email" name="email" class="form-control text-input" />
              <label class="form-label" for="email"><p>Email address</p></label>
            </div>
          
            <!-- Message input -->
            <div class="form-outline mb-4">
              <textarea class="form-control text-input" id="msg" name="msg" rows="4"></textarea>
              <label class="form-label" for="msg"><p>Message</p></label>
            </div>
            
            <div class="form-outline mb-4">
              <label class="form-label" for="msg"><p>{{MSG}}</p></label>
            </div>
          
            <!-- Checkbox -->
           
          
            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-block mb-4">Send</button>
          </form>
    </div>
	</div>

</div>



  <script src="{% static 'js/all.min.js' %}"></script>
	<script src="{% static 'js/mdb.min.js' %}"></script>
	<script src="{% static 'js/contact.js' %}"></script>
</body>
</html>

templates/app/forgetpassword.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>forgot password</title>
	
  <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mdb.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/forgetpassword.css' %}">
	<style>
		body{
			min-height: 100vh;
			background: url("{% static 'images/snow3.jpg' %}") no-repeat fixed;
			background-size: cover;
		}
    .invalidmail{
      color: white;
      font-size: 15px;
      font-weight: 550;
      font-family: monospace;
      
      
    }
	</style>
</head>
<body>
	<nav class="navbar navbar-expand-lg naving">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarRightAlignExample"
      aria-controls="navbarRightAlignExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars text-light m-3"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarRightAlignExample">
      <!-- Left links -->
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:home' %}" >Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:register' %}">Register</a>
        </li>
        {% if user.is_authenticated and not user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:history' %}">History</a>
        </li>
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:login' %}">Login</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:contact' %}" >Contact</a>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<div class="container box">
  {% if MSG %}
    <div class="row justify-content-center">
      <div class="col-md-2">
        
        <p class="invalidmail">{{MSG}}</p>
      </div>
    </div>
{% endif %}
	<div class="row justify-content-center">
    <div class="col-md-4">
      <form method="POST">
        {% csrf_token %}
  <!-- Email input -->
  <div class="form-outline mb-4">
    <input type="text" id="username" name="username" autocomplete="off" class="form-control text-input" />
    <label class="form-label" for="username"><p>Enter Username</p></label>
  </div>

  <!-- Password input -->
  

  

  <!-- Submit button -->
  <button type="submit" class="btn btn-primary btn-block">Get code</button>
</form>
    </div>
		
	</div>
  
</div>
	
	


  <script src="{% static 'js/all.min.js' %}"></script>
	<script src="{% static 'js/mdb.min.js' %}"></script>
</body>
</html>

templates/app/history.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>weather</title>
	
  <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mdb.min.css' %}">
  {% if email %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
  {% else %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/history.css' %}">
  {% endif %}
  
	<style>
		body{
			min-height: 100vh;
			background: url("{% static 'images/snow3.jpg' %}") no-repeat fixed;
			background-size: cover;
		}
        .navbar {
            position: -webkit-sticky;
            position: sticky;
            top: 0;
        }
        
    
	</style>
</head>
<body>
	<nav class="navbar navbar-expand-lg naving">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarRightAlignExample"
      aria-controls="navbarRightAlignExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars text-light m-3"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarRightAlignExample">
      <!-- Left links -->
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:home' %}" >Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:register' %}">Register</a>
        </li>
        {% if user.is_authenticated and not user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:history' %}">History</a>
        </li>
        <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:logout' %}">Logout</a>
          </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:login' %}">Login</a>
        </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:contact' %}" >Contact</a>
          </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>

<div class="container box">
	<div class="row justify-content-center">
    <div class="col-md-4">
      <form method="POST">
        {% csrf_token %}
  <!-- Email input -->
  <div class="form-outline mb-4">
    <input type="text" id="cityortime" name="cityortime" autocomplete="off" required class="form-control text-input" />
    <label class="form-label" for="cityortime"><p>Enter city or Time</p></label>
  </div>
  <!-- Submit button -->
  <button type="submit" class="btn btn-dark btn-rounded">Delete</button>
</form>
    </div>
	</div>
  <br><br>
  <div class="row justify-content-center">
    <div class="col-md-9">
      <table class="table">
        <thead>
          <tr>
            <th scope="col" class="theading">DATE</th>
            <th scope="col" class="theading">TIME</th>
            <th scope="col" class="theading">CITY</th>
            
          </tr>
        </thead>
        <tbody>
            {% for data in history %}
          <tr>
            <td class="tdata"><b>{{data.date}}</b></td>
            <td class="tdata"><b>{{data.time}}</b></td>
            <td class="tdata"><b>{{data.city}}</b></td>

          </tr>
            {% endfor %}
          
        </tbody>
      </table>
    </div>
  </div>

</div>


	
	


  <script src="{% static 'js/all.min.js' %}"></script>
	<script src="{% static 'js/mdb.min.js' %}"></script>
</body>
</html>

templates/app/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>weather</title>
	
  <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mdb.min.css' %}">
  {% if username %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
  {% else %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
  {% endif %}
  
	<style>
		body{
			min-height: 100vh;
			background: url("{% static 'images/snow3.jpg' %}") no-repeat fixed;
			background-size: cover;
		}
    .theading{
      color: white;
      font-weight: 100;
      font: oblique;
      font-size: 16px;   
    }
    .tdata{
      color: white;
      font-size: 13px;   
    }
	</style>
</head>
<body>
	<nav class="navbar navbar-expand-lg">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarRightAlignExample"
      aria-controls="navbarRightAlignExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars text-light m-3"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarRightAlignExample">
      <!-- Left links -->
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:home' %}" >Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:register' %}">Register</a>
        </li>
        {% if user.is_authenticated and not user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:history' %}">History</a>
        </li>
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:login' %}">Login</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:contact' %}" >Contact</a>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
{% if username %}
<div class="container box">
	<div class="row justify-content-center">
    <div class="col-md-4">
      <form method="POST">
        {% csrf_token %}
  <!-- Email input -->
  <div class="form-outline mb-4">
    <input type="text" id="form1Example1" name="city" autocomplete="off" required class="form-control text-input" />
    <label class="form-label" for="form1Example1"><p>Enter city</p></label>
  </div>
  <!-- Submit button -->
  <button type="submit" class="btn btn-dark btn-rounded">Search</button>
</form>
    </div>
	</div>
  <br><br>
  <div class="row justify-content-center">
    <div class="col-md-9">
      <table class="table">
        <thead>
          <tr>
            <th scope="col" class="theading">CITY</th>
            <th scope="col" class="theading">TIME</th>
            <th scope="col" class="theading">TEMPRETURE</th>
            <th scope="col" class="theading">HUMIDITY</th>
            <th scope="col" class="theading">WIND</th>
            <th scope="col" class="theading">DAY</th>
            <th scope="col" class="theading">DESCRIPTION</th>
            <th scope="col" class="theading">    </th>
          </tr>
        </thead>
        <tbody>
          {% if MSG %}

          {% else %}
          <tr>
            <td class="tdata"><b>{{city}}</b></td>
            <td class="tdata"><b>{{time}}</b></td>
            <td class="tdata"><b>{{tempreture}}&#176; C</b></td>
            <td class="tdata"><b>{{humidity}}</b></td>
            <td class="tdata"><b>{{wind_speed}} Kmph</b></td>
            <td class="tdata"><b>{{day}}</b></td>
            <td class="tdata"><b>{{description}}</b></td>
            <td class="tdata"><p><img src="https://api.openweathermap.org/img/w/{{icon}}.png" width="60px"></p></td>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
  <br><br><br><br>
  <div class="row justify-content-center">
    <div class="col-md-3">
      <h4 style="color: white;">{{MSG}}</h4>
    </div>
  </div>
  
</div>

{% else %}
<div class="container box">
	<div class="row">
		<div class="col-md-12">
			<h1>Welcome To Weather Forcasting Web-application</h1>
		</div>
		<div class="col-md-12">
			<p>To Know Current Weather Information, Open Your Account And Search City Name. <br>Allow users to know the weather report in detail. Let them know what will be the weather in the morning, <br> how cold or hot it will be during the night. Users want to know everything about and around them</p>
		</div>
	</div>
</div>
{% endif %}
	
	


  <script src="{% static 'js/all.min.js' %}"></script>
	<script src="{% static 'js/mdb.min.js' %}"></script>
</body>
</html>

templates/app/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>login page</title>
	
  <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mdb.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
	<style>
		body{
			min-height: 100vh;
			background: url("{% static 'images/snow3.jpg' %}") no-repeat fixed;
			background-size: cover;
		}
    .invaliduser{
      color: white;
      font-size: 14px;
      font-weight: 550;
      font-family: monospace;
    }


	</style>
</head>
<body>
	<nav class="navbar navbar-expand-lg">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarRightAlignExample"
        aria-controls="navbarRightAlignExample"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars text-light m-3"></i>
      </button>
  
      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarRightAlignExample">
        <!-- Left links -->
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          
          <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:home' %}" >Home</a>
          </li>
  
          <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:register' %}">Register</a>
          </li>
          {% if user.is_authenticated and not user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:history' %}">History</a>
          </li>
          <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:login' %}">Login</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link item" href="{% url 'app:contact' %}" >Contact</a>
          </li>
        </ul>
        <!-- Left links -->
      </div>
      <!-- Collapsible wrapper -->
    </div>
    <!-- Container wrapper -->
  </nav>
<div class="container box">
	<div class="row justify-content-center">

    <div class="col-md-4 ">
      <form method="POST">
        {% csrf_token %}
  <!-- Email input -->
  <div class="form-outline mb-4">
    <input type="text" id="username" name="username" autocomplete="off"  required="True" class="form-control text-input" />
    <label class="form-label" for="username"><p>Username</p></label>
  </div>

  <!-- Password input -->
  <div class="form-outline mb-4">
    <input type="password" id="password" name="password" autocomplete="off"  required="True" class="form-control text-input" />
    <label class="form-label" for="password"><p>Password</p></label>
  </div>

  <!-- 2 column grid layout for inline styling -->
  <div class="form-outline mb-4 ">

    <div class="col justify-content-center">
      <!-- Simple link -->
      <a href="{% url 'app:forgetpassword' %}"><p>I forgot my password ?</p></a>
    </div>
  </div>


  

  <!-- Submit button -->
  <button type="submit" class="btn btn-primary btn-block">Sign in</button>
</form>
    </div>
		
	</div>
  {% if MSG %}
    <div class="row justify-content-center">
      <div class="col-md-2">
        <br><br>
        <p class="invaliduser">{{MSG}}</p>
      </div>
    </div>
{% endif %}
</div>
	
	


  <script src="{% static 'js/all.min.js' %}"></script>
	<script src="{% static 'js/mdb.min.js' %}"></script>
  <script>
    window.addEventListener('load', function () {
      var usernameInput = document.getElementById('username');
      var passwordInput = document.getElementById('password');

      usernameInput.value = '';
      passwordInput.value = '';
  });
  

  </script>
</body>
</html>

templates/app/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Registration page</title>
	
  <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mdb.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
	<style>
		body{
			min-height: 100vh;
			background: url("{% static 'images/snow3.jpg' %}") no-repeat fixed;
			background-size: cover;
		}
  
   
	</style>
</head>
<body>
	<nav class="navbar navbar-expand-lg naving">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarRightAlignExample"
      aria-controls="navbarRightAlignExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars text-light m-3"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarRightAlignExample">
      <!-- Left links -->
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:home' %}" >Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:register' %}">Register</a>
        </li>
        {% if user.is_authenticated and not user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:history' %}">History</a>
        </li>
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:login' %}">Login</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link item" href="{% url 'app:contact' %}" >Contact</a>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<div class="container box">
	<div class="row justify-content-center">
    <div class="col-md-4">
      <form method="POST" id="myform" autocomplete="off" onsubmit="return validateform()">
        {% csrf_token %}
  <!-- 2 column grid layout with text inputs for the first and last names -->
  <div class="row mb-4">
    <div class="col">
      <div class="form-outline">
        <input type="text" id="firstname" name="firstname" required autocomplete="off" class="form-control text-input" />
        <label class="form-label" for="firstname"><p>First name</p></label>
      </div>
    </div>
    <div class="col">
      <div class="form-outline">
        <input type="text" id="lastname" name="lastname" required autocomplete="off" class="form-control text-input" />
        <label class="form-label" for="lastname"><p>Last name</p></label>
      </div>
    </div>
  </div>

  <!-- Email input -->
  <div class="form-outline mb-4">
    <input type="email" id="email" name="email" required autocomplete="off" class="form-control text-input" />
    <label class="form-label" for="email"><p>Email address</p></label>
  </div>



<!-- user input -->
  <div class="form-outline mb-4">
    <input type="text" id="username" name="username" required autocomplete="off" class="form-control text-input" />
    <label class="form-label" for="username"><p>Username</p></label>
  </div>

  <!-- Password input -->
  <div class="form-outline mb-4">
    <input type="password" id="password" name="password" required autocomplete="off" class="form-control text-input" />
    <label class="form-label" for="password"><p>Password</p></label>
  </div>

  <!-- Submit button -->
  <button type="submit" class="btn btn-primary btn-block mb-4">Sign up</button><br><br>
</form>
      </div>
      
      
      <div class="row justify-content-center">
        <div class="col-md-4">
          <h5 style="color: white; font: 20px; margin-left: 55px;">{{MSG}}</h5>
        </div>
      </div>
		
	</div>
</div>




  <script src="{% static 'js/all.min.js' %}"></script>
  <script src="{% static 'js/register.js' %}"></script>
  <script src="{% static 'js/mdb.min.js' %}"></script>
</body>
</html>